/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_MACHINE_MACHINE_PB_H_INCLUDED
#define PB_MACHINE_MACHINE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _machine_PingResponse { 
    uint32_t number;
} machine_PingResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define machine_PingResponse_init_default        {0}
#define machine_PingResponse_init_zero           {0}

/* Field tags (for use in manual encoding/decoding) */
#define machine_PingResponse_number_tag          1

/* Struct field encoding specification for nanopb */
#define machine_PingResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   number,            1)
#define machine_PingResponse_CALLBACK NULL
#define machine_PingResponse_DEFAULT NULL

extern const pb_msgdesc_t machine_PingResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define machine_PingResponse_fields &machine_PingResponse_msg

/* Maximum encoded size of messages (where known) */
#define machine_PingResponse_size                6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
