/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "machine.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(machine_PingResponse, machine_PingResponse, AUTO)


PB_BIND(machine_PipetteState, machine_PipetteState, AUTO)


PB_BIND(machine_CollectionRequest, machine_CollectionRequest, AUTO)


PB_BIND(machine_MovementDetails, machine_MovementDetails, AUTO)


PB_BIND(machine_FluidRequest, machine_FluidRequest, AUTO)


PB_BIND(machine_FluidDetails, machine_FluidDetails, AUTO)


PB_BIND(machine_StateReport, machine_StateReport, AUTO)


PB_BIND(machine_StateReportList, machine_StateReportList, AUTO)






