package topics_backend

const (
	PAYLOAD_SMART_SWITCH_OFF string = "OFF"
	PAYLOAD_SMART_SWITCH_ON string = "ON"
	TOPIC_CLOSE_BLIND string = "asol/close_bedroom_blind"
	TOPIC_KV_GET string = "asol/kv/get/"
	TOPIC_KV_GET_RESP string = "asol/kv/get-resp/"
	TOPIC_KV_SET string = "asol/kv/set/"
	TOPIC_KV_SET_RESP string = "asol/kv/set-resp/"
	TOPIC_MONITOR_OFF string = "asol/monitor_off"
	TOPIC_MONITOR_ON string = "asol/monitor_on"
	TOPIC_OPEN_BLIND string = "asol/open_bedroom_blind"
	TOPIC_SESSION_BEGAN string = "asol/session/began"
	TOPIC_SESSION_BEGIN string = "asol/session/begin"
	TOPIC_SESSION_END string = "asol/session/end"
	TOPIC_SESSION_ENDED string = "asol/session/ended"
	TOPIC_SESSION_PAUSE string = "asol/session/pause"
	TOPIC_SESSION_PAUSED string = "asol/session/paused"
	TOPIC_SESSION_RESUME string = "asol/session/resume"
	TOPIC_SESSION_RESUMED string = "asol/session/resumed"
	TOPIC_SESSION_STATUS_GET string = "asol/session/status-get"
	TOPIC_SESSION_STATUS_RESP string = "asol/session/status-resp"
	TOPIC_SMART_SWITCH string = "cmnd/tasmota_sw1/Power1"
	TOPIC_STATE_REPORT_JSON string = "asol/state-report-json"
	TOPIC_STREAM_END string = "asol/stream/end"
	TOPIC_STREAM_START string = "asol/stream/begin"
	TOPIC_STREAM_STATUS_GET string = "asol/stream/status-get"
	TOPIC_STREAM_STATUS_RESP string = "asol/stream/status-resp"
	TOPIC_TRIGGER_DSLR string = "asol/dslr-crop-capture"
	TOPIC_TRIGGER_DSLR_RESP string = "asol/dslr-crop-capture-resp"
)
