/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_MACHINE_PB_H_INCLUDED
#define PB_MACHINE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PingResponse { 
    pb_callback_t message;
} PingResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PingResponse_init_default                {{{NULL}, NULL}}
#define PingResponse_init_zero                   {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define PingResponse_message_tag                 1

/* Struct field encoding specification for nanopb */
#define PingResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   message,           1)
#define PingResponse_CALLBACK pb_default_field_callback
#define PingResponse_DEFAULT NULL

extern const pb_msgdesc_t PingResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PingResponse_fields &PingResponse_msg

/* Maximum encoded size of messages (where known) */
/* PingResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
